// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package go4c_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CmdLogin 登录参数
type CmdLogin struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ClientId             string   `protobuf:"bytes,5,opt,name=clientId,proto3" json:"clientId,omitempty"`
	UserAgent            string   `protobuf:"bytes,6,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdLogin) Reset()         { *m = CmdLogin{} }
func (m *CmdLogin) String() string { return proto.CompactTextString(m) }
func (*CmdLogin) ProtoMessage()    {}
func (*CmdLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *CmdLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdLogin.Unmarshal(m, b)
}
func (m *CmdLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdLogin.Marshal(b, m, deterministic)
}
func (m *CmdLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdLogin.Merge(m, src)
}
func (m *CmdLogin) XXX_Size() int {
	return xxx_messageInfo_CmdLogin.Size(m)
}
func (m *CmdLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdLogin.DiscardUnknown(m)
}

var xxx_messageInfo_CmdLogin proto.InternalMessageInfo

func (m *CmdLogin) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *CmdLogin) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *CmdLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CmdLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CmdLogin) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *CmdLogin) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func init() {
	proto.RegisterType((*CmdLogin)(nil), "go4c_proto.CmdLogin")
}

func init() {
	proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899)
}

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0xcf, 0x37, 0x49, 0x8e, 0x07, 0xb3, 0x95, 0x96,
	0x30, 0x72, 0x71, 0x38, 0xe7, 0xa6, 0xf8, 0xe4, 0xa7, 0x67, 0xe6, 0x09, 0x09, 0x71, 0xb1, 0x64,
	0xe4, 0x17, 0x97, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x20, 0xb1, 0x82, 0xfc,
	0xa2, 0x12, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x30, 0x5b, 0x48, 0x8a, 0x8b, 0xa3, 0xb4,
	0x38, 0xb5, 0x28, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x19, 0xac, 0x16, 0xce, 0x07, 0xc9, 0x15, 0x24,
	0x16, 0x17, 0x97, 0xe7, 0x17, 0xa5, 0x48, 0xb0, 0x40, 0xe4, 0x60, 0x7c, 0x90, 0x5c, 0x72, 0x4e,
	0x66, 0x6a, 0x5e, 0x89, 0x67, 0x8a, 0x04, 0x2b, 0x44, 0x0e, 0xc6, 0x17, 0x92, 0xe1, 0xe2, 0x04,
	0x99, 0xe1, 0x98, 0x9e, 0x9a, 0x57, 0x22, 0xc1, 0x06, 0x96, 0x44, 0x08, 0x24, 0xb1, 0x81, 0x5d,
	0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x35, 0x9a, 0xde, 0x31, 0xc6, 0x00, 0x00, 0x00,
}
